import React, { useMemo, useState } from 'react';
import { 
  ResponsiveContainer, 
  Sankey, 
  Tooltip, 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Legend, 
  PieChart, 
  Pie, 
  Cell,
  Layer,
  Rectangle
} from 'recharts';
import { Tool, ToolTransaction, ProductionLine } from '../types';
import { LayoutDashboard, TrendingUp, Trash2, Box, Activity, AlertCircle } from 'lucide-react';
import { motion } from 'motion/react';

interface ToolDashboardProps {
  tools: Tool[];
  transactions: ToolTransaction[];
  lines: ProductionLine[];
  isAdmin?: boolean;
}

const COLORS = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6', '#ec4899', '#06b6d4', '#f97316'];

export const ToolDashboard: React.FC<ToolDashboardProps> = ({ tools, transactions, lines, isAdmin = false }) => {
  const [selectedFactory, setSelectedFactory] = useState<string>('Todas');
  const [selectedLine, setSelectedLine] = useState<string>('Todas');

  const factories = useMemo(() => {
    const factorySet = new Set<string>();
    lines.forEach(line => {
      const match = line.name.match(/^[a-zA-Z]+/);
      if (match) {
        factorySet.add(match[0].toUpperCase());
      }
    });
    return Array.from(factorySet).sort();
  }, [lines]);
  
  // 1. Sankey Data: Tools -> Lines
  const sankeyData = useMemo(() => {
    const toolLineDistribution = new Map<string, number>();
    
    // Sort transactions by date to process them in order
    const sortedTransactions = [...transactions].sort((a, b) => 
      (a.createdAt?.toMillis?.() || 0) - (b.createdAt?.toMillis?.() || 0)
    );
    
    sortedTransactions.forEach(t => {
      if (!t.line) return;
      const key = `${t.toolId}_${t.line}`;
      const current = toolLineDistribution.get(key) || 0;
      
      const isAutoGenerated = (t as any).isAutoGenerated === true;
      
      // Lógica de Contagem para ferramentas na máquina:
      // - Saída normal (+1)
      // - Retorno Almoxarifado (-1)
      // - Retorno Descarte "isAutoGenerated" (-1)
      // - Saída Substituição (+1)
      // O saldo final na máquina se mantém quando há substituição (+1 e -1 = 0)
      
      if (t.type === 'Saída') {
        toolLineDistribution.set(key, current + t.quantity);
      } else if (t.type === 'Retorno') {
        toolLineDistribution.set(key, Math.max(0, current - t.quantity));
      }
    });

    const filteredDistribution = new Map<string, number>();
    const activeTools = new Set<string>();
    const activeLines = new Set<string>();

    toolLineDistribution.forEach((value, key) => {
      if (value <= 0) return;
      const [toolId, lineName] = key.split('_');
      
      // Apply filters
      if (selectedFactory !== 'Todas') {
        if (!lineName.toUpperCase().startsWith(selectedFactory)) return;
      }
      if (selectedLine !== 'Todas') {
        if (lineName !== selectedLine) return;
      }

      filteredDistribution.set(key, value);
      activeTools.add(toolId);
      activeLines.add(lineName);
    });

    const nodes: { name: string, type?: string }[] = [];
    const links: { source: number; target: number; value: number }[] = [];
    const toolMap = new Map<string, number>();
    const lineMap = new Map<string, number>();
    let nodeIndex = 0;
    
    const toolNames: string[] = [];
    const lineNames: string[] = [];
    
    // Add active tools
    tools.forEach(tool => {
      if (activeTools.has(tool.id)) {
        nodes.push({ name: tool.name, type: 'tool' });
        toolMap.set(tool.id, nodeIndex++);
        toolNames.push(tool.name);
      }
    });
    
    // Add active lines
    lines.forEach(line => {
      if (activeLines.has(line.name)) {
        nodes.push({ name: line.name, type: 'line' });
        lineMap.set(line.name, nodeIndex++);
        lineNames.push(line.name);
      }
    });
    
    // Create links
    filteredDistribution.forEach((value, key) => {
      const [toolId, lineName] = key.split('_');
      const source = toolMap.get(toolId);
      const target = lineMap.get(lineName);
      
      if (source !== undefined && target !== undefined) {
        links.push({ source, target, value });
      }
    });
    
    return { nodes, links, toolNames, lineNames };
  }, [tools, transactions, lines, selectedFactory, selectedLine]);

  const getLineColor = React.useCallback((lineName: string) => {
    const index = sankeyData.lineNames.indexOf(lineName);
    return COLORS[index % COLORS.length] || '#94a3b8';
  }, [sankeyData.lineNames]);

  const CustomSankeyNode = React.useCallback((props: any) => {
    const { x, y, width, height, index, payload } = props;
    const isLine = payload.type === 'line';
    const isSource = payload.type === 'tool';
    const fill = isLine ? getLineColor(payload.name) : '#3b82f6';
    
    return (
      <Layer key={`CustomNode${index}`}>
        <Rectangle x={x} y={y} width={width} height={height} fill={fill} fillOpacity={1} rx={2} />
        <text
          textAnchor={isSource ? 'start' : 'end'}
          x={isSource ? x : x + width}
          y={y - 6}
          fontSize="11"
          fontWeight="600"
          fill="#374151"
        >
          {payload.name}
        </text>
      </Layer>
    );
  }, [getLineColor]);

  const CustomSankeyLink = React.useCallback((props: any) => {
    const { sourceX, targetX, sourceY, targetY, sourceControlX, targetControlX, linkWidth, payload } = props;
    const targetNode = typeof payload.target === 'object' ? payload.target : sankeyData.nodes[payload.target];
    const fill = targetNode ? getLineColor(targetNode.name) : '#cbd5e1';
    
    return (
      <path
        d={`
          M${sourceX},${sourceY + linkWidth / 2}
          C${sourceControlX},${sourceY + linkWidth / 2} ${targetControlX},${targetY + linkWidth / 2} ${targetX},${targetY + linkWidth / 2}
          L${targetX},${targetY - linkWidth / 2}
          C${targetControlX},${targetY - linkWidth / 2} ${sourceControlX},${sourceY - linkWidth / 2} ${sourceX},${sourceY - linkWidth / 2}
          Z
        `}
        fill={fill}
        fillOpacity={0.3}
        className="hover:fill-opacity-60 transition-all duration-300"
      />
    );
  }, [getLineColor, sankeyData]);

  // 2. Consumption Data: Top 10 most used tools
  const consumptionData = useMemo(() => {
    const consumptionMap = new Map<string, number>();
    
    transactions.forEach(t => {
      if (t.type === 'Saída') {
        consumptionMap.set(t.toolName, (consumptionMap.get(t.toolName) || 0) + t.quantity);
      }
    });
    
    return Array.from(consumptionMap.entries())
      .map(([name, value]) => ({ name, value }))
      .sort((a, b) => b.value - a.value)
      .slice(0, 10);
  }, [transactions]);

  // 3. Discard Data: Reasons for return (excluding 'Retorno Almoxarifado')
  const discardData = useMemo(() => {
    const discardMap = new Map<string, number>();
    
    transactions.forEach(t => {
      if (t.type === 'Retorno' && t.reason !== 'Retorno Almoxarifado') {
        discardMap.set(t.reason, (discardMap.get(t.reason) || 0) + t.quantity);
      }
    });
    
    return Array.from(discardMap.entries())
      .map(([name, value]) => ({ name, value }));
  }, [transactions]);

  // 4. Summary Stats
  const stats = useMemo(() => {
    const totalInUse = tools.reduce((acc, t) => acc + t.inUse, 0);
    const totalStock = tools.reduce((acc, t) => acc + t.stock, 0);
    const totalDiscards = transactions
      .filter(t => t.type === 'Retorno' && t.reason !== 'Retorno Almoxarifado')
      .reduce((acc, t) => acc + t.quantity, 0);
    
    const assetValueStock = tools.reduce((acc, t) => acc + (t.stock * (t.price || 0)), 0);
    const assetValueInUse = tools.reduce((acc, t) => acc + (t.inUse * (t.price || 0)), 0);
    
    let totalDiscardCost = 0;
    const discardDataCosts = new Map<string, number>();

    transactions.forEach(t => {
      if (t.type === 'Retorno' && t.reason !== 'Retorno Almoxarifado') {
        const tool = tools.find(tl => tl.id === t.toolId);
        const cost = t.quantity * (tool?.price || 0);
        totalDiscardCost += cost;
        discardDataCosts.set(t.reason, (discardDataCosts.get(t.reason) || 0) + cost);
      }
    });

    const discardCostsArray = Array.from(discardDataCosts.entries())
      .map(([name, value]) => ({ name, value }));

    return { totalInUse, totalStock, totalDiscards, assetValueStock, assetValueInUse, totalDiscardCost, discardCostsArray };
  }, [tools, transactions]);

  if (sankeyData.nodes.length === 0 || sankeyData.links.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-96 bg-white rounded-2xl border border-dashed border-gray-300">
        <Activity className="w-12 h-12 text-gray-300 mb-2" />
        <p className="text-gray-500 font-medium">Sem dados de movimentação suficientes.</p>
        <p className="text-sm text-gray-400">Registre saídas e retornos de ferramentas para visualizar o fluxo por linha.</p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100"
        >
          <div className="flex items-center gap-4 border-b border-gray-50 pb-4 mb-4">
            <div className="p-3 bg-blue-50 rounded-xl">
              <Box className="w-6 h-6 text-blue-600" />
            </div>
            <div>
              <p className="text-sm font-medium text-gray-500">Ferramentas em Uso</p>
              <p className="text-2xl font-bold text-gray-900">{stats.totalInUse}</p>
            </div>
          </div>
          {isAdmin && (
            <p className="text-xs text-gray-500 font-medium">Patrimônio: <span className="text-green-600 font-bold">R$ {stats.assetValueInUse.toFixed(2).replace('.', ',')}</span></p>
          )}
        </motion.div>

        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100"
        >
          <div className="flex items-center gap-4 border-b border-gray-50 pb-4 mb-4">
            <div className="p-3 bg-green-50 rounded-xl">
              <TrendingUp className="w-6 h-6 text-green-600" />
            </div>
            <div>
              <p className="text-sm font-medium text-gray-500">Em Estoque</p>
              <p className="text-2xl font-bold text-gray-900">{stats.totalStock}</p>
            </div>
          </div>
          {isAdmin && (
            <p className="text-xs text-gray-500 font-medium">Patrimônio: <span className="text-green-600 font-bold">R$ {stats.assetValueStock.toFixed(2).replace('.', ',')}</span></p>
          )}
        </motion.div>

        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100"
        >
          <div className="flex items-center gap-4 border-b border-gray-50 pb-4 mb-4">
            <div className="p-3 bg-red-50 rounded-xl">
              <Trash2 className="w-6 h-6 text-red-600" />
            </div>
            <div>
              <p className="text-sm font-medium text-gray-500">Total Descartes</p>
              <p className="text-2xl font-bold text-gray-900">{stats.totalDiscards}</p>
            </div>
          </div>
          {isAdmin && (
            <p className="text-xs text-gray-500 font-medium">Perda Estimada: <span className="text-red-600 font-bold">R$ {stats.totalDiscardCost.toFixed(2).replace('.', ',')}</span></p>
          )}
        </motion.div>

        {isAdmin && (
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
            className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 flex flex-col justify-center bg-gradient-to-br from-gray-900 to-gray-800"
          >
            <p className="text-sm font-medium text-gray-400 mb-1">Patrimônio Total Ativo</p>
            <p className="text-3xl font-black text-white">R$ {(stats.assetValueStock + stats.assetValueInUse).toFixed(2).replace('.', ',')}</p>
            <div className="w-full bg-gray-700 h-1.5 rounded-full mt-4 overflow-hidden flex">
              {stats.assetValueStock + stats.assetValueInUse > 0 && (
                <>
                  <div title="Estoque" className="bg-green-500 h-full" style={{ width: `${(stats.assetValueStock / (stats.assetValueStock + stats.assetValueInUse)) * 100}%` }}></div>
                  <div title="Em Uso" className="bg-blue-500 h-full" style={{ width: `${(stats.assetValueInUse / (stats.assetValueStock + stats.assetValueInUse)) * 100}%` }}></div>
                </>
              )}
            </div>
          </motion.div>
        )}
      </div>

      {/* Low Stock Alerts */}
      {tools.filter(t => t.stock <= (t.minStock || 0)).length > 0 && (
        <motion.div 
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="bg-red-50 p-4 rounded-xl border border-red-100 mb-6 flex flex-col sm:flex-row gap-4"
        >
          <div className="flex-shrink-0">
            <div className="w-10 h-10 bg-red-100 flex items-center justify-center rounded-full text-red-600">
              <AlertCircle className="w-6 h-6" />
            </div>
          </div>
          <div>
            <h4 className="text-red-800 font-bold mb-1">Atenção: Ferramentas com Estoque Baixo</h4>
            <div className="flex flex-wrap gap-2">
              {tools.filter(t => t.stock <= (t.minStock || 0)).map(t => (
                <span key={t.id} className="bg-white border border-red-200 text-red-700 text-xs px-2 py-1 rounded-md font-medium">
                  {t.name} (Atual: {t.stock} / Mín: {t.minStock})
                </span>
              ))}
            </div>
          </div>
        </motion.div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mt-6">
        {/* Sankey Chart: Tools to Lines */}
        <motion.div 
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 lg:col-span-2"
        >
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-6 gap-4">
            <h3 className="text-lg font-bold text-gray-900 flex items-center gap-2">
              <Activity className="w-5 h-5 text-blue-600" />
              Fluxo de Ferramentas por Linha
            </h3>
            <div className="flex flex-wrap items-center gap-3">
              <select
                value={selectedFactory}
                onChange={(e) => {
                  setSelectedFactory(e.target.value);
                  setSelectedLine('Todas');
                }}
                className="p-2 border border-gray-200 rounded-lg text-sm bg-gray-50 focus:bg-white transition-colors"
              >
                <option value="Todas">Todas as Fábricas</option>
                {factories.map(f => (
                  <option key={f} value={f}>Fábrica {f}</option>
                ))}
              </select>
              
              <select
                value={selectedLine}
                onChange={(e) => setSelectedLine(e.target.value)}
                className="p-2 border border-gray-200 rounded-lg text-sm bg-gray-50 focus:bg-white transition-colors"
              >
                <option value="Todas">Todas as Linhas</option>
                {lines
                  .filter(l => selectedFactory === 'Todas' || l.name.toUpperCase().startsWith(selectedFactory))
                  .map(l => (
                    <option key={l.id} value={l.name}>{l.name}</option>
                  ))
                }
              </select>
            </div>
          </div>
          <div className="h-[600px] w-full flex flex-col">
            {sankeyData.nodes.length > 0 ? (
              <>
                <div className="flex-1 min-h-0">
                  <ResponsiveContainer width="100%" height="100%">
                    <Sankey
                      data={sankeyData}
                      nodePadding={24}
                      margin={{ left: 20, right: 20, top: 30, bottom: 20 }}
                      node={CustomSankeyNode}
                      link={CustomSankeyLink}
                    >
                      <Tooltip 
                        contentStyle={{ borderRadius: '16px', border: 'none', boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)' }}
                      />
                    </Sankey>
                  </ResponsiveContainer>
                </div>
                {/* Legend */}
                <div className="mt-4 pt-4 border-t border-gray-100 flex flex-wrap items-center justify-center gap-4">
                  <div className="flex items-center gap-2 mr-4">
                    <div className="w-3 h-3 rounded-full bg-blue-500" />
                    <span className="text-xs font-bold text-gray-600">Ferramentas</span>
                  </div>
                  {sankeyData.lineNames.map(line => (
                    <div key={line} className="flex items-center gap-2">
                      <div className="w-3 h-3 rounded-full" style={{ backgroundColor: getLineColor(line) }} />
                      <span className="text-xs font-bold text-gray-600">{line}</span>
                    </div>
                  ))}
                </div>
              </>
            ) : (
              <div className="w-full h-full flex items-center justify-center text-gray-400 font-bold">
                Nenhum dado encontrado para os filtros selecionados.
              </div>
            )}
          </div>
        </motion.div>

        {/* Bar Chart: Consumption */}
        <motion.div 
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100"
        >
          <h3 className="text-lg font-bold text-gray-900 mb-6 flex items-center gap-2">
            <TrendingUp className="w-5 h-5 text-green-600" />
            Top 10 Consumo (Saídas)
          </h3>
          <div className="h-[300px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={consumptionData} layout="vertical" margin={{ left: 40 }}>
                <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#f3f4f6" />
                <XAxis type="number" hide />
                <YAxis 
                  dataKey="name" 
                  type="category" 
                  width={100} 
                  tick={{ fontSize: 10, fontWeight: 500 }}
                  axisLine={false}
                  tickLine={false}
                />
                <Tooltip 
                  cursor={{ fill: '#f9fafb' }}
                  contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)' }}
                />
                <Bar dataKey="value" fill="#3b82f6" radius={[0, 4, 4, 0]} barSize={20} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </motion.div>

        {/* Pie Chart: Discard Reasons */}
        <motion.div 
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100"
        >
          <h3 className="text-lg font-bold text-gray-900 mb-6 flex items-center gap-2">
            <Trash2 className="w-5 h-5 text-red-600" />
            Quantidade de Descartes
          </h3>
          <div className="h-[300px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={discardData}
                  cx="50%"
                  cy="50%"
                  innerRadius={60}
                  outerRadius={80}
                  paddingAngle={5}
                  dataKey="value"
                >
                  {discardData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                  ))}
                </Pie>
                <Tooltip 
                  contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)' }}
                />
                <Legend verticalAlign="bottom" height={36} iconType="circle" />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </motion.div>

        {/* Bar Chart: Financial Impact */}
        <motion.div 
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 lg:col-span-2"
        >
          <h3 className="text-lg font-bold text-gray-900 mb-6 flex items-center gap-2">
            <TrendingUp className="w-5 h-5 text-red-600" />
            Impacto Financeiro de Quebras/Descartes
          </h3>
          <div className="h-[300px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={stats.discardCostsArray} margin={{ top: 20, right: 30, left: 20, bottom: 5 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f3f4f6" />
                <XAxis dataKey="name" tick={{ fontSize: 12, fontWeight: 500 }} axisLine={false} tickLine={false} />
                <YAxis 
                  tickFormatter={(value) => `R$ ${value}`}
                  tick={{ fontSize: 12 }} axisLine={false} tickLine={false} 
                />
                <Tooltip 
                  formatter={(value: number) => [`R$ ${value.toFixed(2)}`, 'Custo']}
                  cursor={{ fill: '#f9fafb' }}
                  contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)' }}
                />
                <Bar dataKey="value" radius={[4, 4, 0, 0]} barSize={40}>
                   {stats.discardCostsArray.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={COLORS[(index + 3) % COLORS.length]} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </motion.div>
      </div>
    </div>
  );
};
